[project]
name = "chatgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.30.0",
    "chainlit>=2.0.2",
    "fastapi>=0.115.6",
    "langchain>=0.3.14",
    "ollama>=0.4.5",
]
